variables:
  PKGNAME: ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.gz
  URL: https://wge-staging.sidvind.com/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}

image: node:8

stages:
  - prepare
  - test
  - build
  - release
  - stage

Install dependencies:
  stage: prepare
  tags:
    - docker
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-node_modules
    expire_in: 1 week
    paths:
      - node_modules/
  cache:
    key: "${CI_JOB_NAME}/${CI_COMMIT_REF_NAME}"
    paths:
      - node_modules/
  script:
   - npm install

Code lint:
  stage: test
  tags:
    - docker
  script:
    - node_modules/.bin/grunt lint

Karma:
  stage: test
  image: docker.sidvind.com/chrome
  tags:
    - docker
  script:
    - node_modules/.bin/grunt build:data karma:default

Build:
  stage: build
  image: docker.sidvind.com/chrome
  tags:
    - docker
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-build
    expire_in: 1 week
    when: always
    paths:
      - build
      - public
  script:
    - node_modules/.bin/grunt build

Tarball:
  stage: release
  tags:
    - docker
  artifacts:
    name: $PKGNAME
    expire_in: 1 week
    paths:
      - $PKGNAME
  script:
    - node_modules/.bin/grunt compress manifest
    - cat manifest.json
    - tar pcvzf $PKGNAME --transform 's#public/##g' --show-transformed-names public manifest.json *.zip

Deploy:
  stage: stage
  only:
    - tags
  dependencies:
    - Tarball
  tags:
    - nodejs
  environment:
    name: ${CI_COMMIT_TAG}
    url: ${URL}
  script:
    - /bin/zsh -c 'ssh -Ti =(echo $SSH_KEY) deploy@sidvind.com < $PKGNAME'
