image: node:8

cache:
  paths:
    - node_modules/

stages:
  - prepare
  - test
  - build
  - release

Install dependencies:
  stage: prepare
  tags:
    - docker
  artifacts:
    untracked: true
  script:
   - npm install

Code lint:
  stage: test
  tags:
    - docker
  script:
    - node_modules/.bin/grunt lint

Karma:
  stage: test
  image: docker.sidvind.com/chrome
  tags:
    - docker
  script:
    - node_modules/.bin/grunt build:data karma:default

Build:
  stage: build
  image: docker.sidvind.com/chrome
  tags:
    - docker
  artifacts:
    untracked: true
  script:
    - node_modules/.bin/grunt build

Release:
  stage: release
  only:
    - tags
  tags:
    - docker
  script:
    - node_modules/.bin/grunt compress
