image: node:8

cache:
  key: "${CI_JOB_NAME}/${CI_COMMIT_REF_NAME}"
  paths:
    - node_modules/

stages:
  - prepare
  - test
  - build
  - release

Install dependencies:
  stage: prepare
  tags:
    - docker
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-node_modules
    expire_in: 1 week
    untracked: true
  script:
   - npm install

Code lint:
  stage: test
  tags:
    - docker
  script:
    - node_modules/.bin/grunt lint

Karma:
  stage: test
  image: docker.sidvind.com/chrome
  tags:
    - docker
  script:
    - node_modules/.bin/grunt build:data karma:default

Build:
  stage: build
  image: docker.sidvind.com/chrome
  tags:
    - docker
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-build
    expire_in: 1 week
    when: always
    paths:
      - build
      - public
  script:
    - node_modules/.bin/grunt build

Release:
  stage: release
  only:
    - tags
  tags:
    - docker
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_PIPELINE_ID}-release
    when: always
    paths:
      - "*.zip"
  script:
    - node_modules/.bin/grunt compress
